import type { PricingRow } from "../pricing";

export const OPENAI_PRICING: PricingRow[] = [
  // ==========================================================================
  // OpenAI — developers.openai.com/api/docs/pricing（标准档、短上下文）
  // 核对日期 2026-10-08；gpt-6.1-sol / gpt-6-luna 另见 /api/docs/models/<id>
  //
  // 超过 272K 输入的长上下文档：输入与缓存 ×2、输出 ×1.5（整次请求），
  // 例如 6.1 sol 4/15、6 luna 0.2/0.75、5.6 sol 8/30。此处取短上下文：
  // 编码 agent 绝大多数请求在阈值以内，按长上下文价算会普遍高估。
  // ==========================================================================
  {
    // 2026-10 新增。必须排在 gpt-6-astra 之前：astra 的 \bgpt-6\b 兜底
    // 会把 gpt-6.1-sol / gpt-6-luna 也吃掉（"-" 与 "." 都算词边界）
    key: "gpt-6.1-sol",
    label: "GPT-6.1 Sol",
    match: /gpt[.\-_]*6[.\-_]*1[.\-_]*sol/i,
    inputPerM: 2,
    outputPerM: 10,
    cacheReadPerM: 0.1,
    cacheWritePerM: 2.5,
    currency: "USD",
  },
  {
    // 2026-10 新增，同上须排在 gpt-6-astra 之前
    key: "gpt-6-luna",
    label: "GPT-6 Luna",
    match: /gpt[.\-_]*6[.\-_]*luna/i,
    inputPerM: 0.1,
    outputPerM: 0.5,
    cacheReadPerM: 0.01,
    cacheWritePerM: 0.125,
    currency: "USD",
  },
  {
    key: "gpt-6-astra",
    label: "GPT-6 Astra",
    // 不能写成 gpt-6 宽松匹配，否则会吃掉 gpt-5.6
    match: /gpt[.\-_]*6[.\-_]*astra|\bgpt-6\b/i,
    inputPerM: 10,
    outputPerM: 50,
    cacheReadPerM: 1,
    cacheWritePerM: 12.5,
    currency: "USD",
  },
  {
    key: "gpt-5.6-sol",
    label: "GPT-5.6 Sol",
    match: /5[.-]6[.\-_]*sol|daybreak[.\-_]*blue/i,
    // 促销价，官方注明至少持续到 2026-11-21；原价请留意官网
    inputPerM: 4,
    outputPerM: 20,
    cacheReadPerM: 0.4,
    cacheWritePerM: 5,
    currency: "USD",
  },
  {
    key: "gpt-5.6-terra",
    label: "GPT-5.6 Terra",
    match: /5[.-]6[.\-_]*terra/i,
    inputPerM: 2,
    outputPerM: 12,
    cacheReadPerM: 0.2,
    cacheWritePerM: 2.5,
    currency: "USD",
  },
  {
    key: "gpt-5.6-luna",
    label: "GPT-5.6 Luna",
    match: /5[.-]6[.\-_]*luna/i,
    inputPerM: 0.2,
    outputPerM: 1.2,
    cacheReadPerM: 0.02,
    cacheWritePerM: 0.25,
    currency: "USD",
  },
  {
    key: "gpt-5.6-cyber",
    label: "GPT-5.6 Cyber",
    match: /5[.-]6[.\-_]*cyber|daybreak[.\-_]*red/i,
    inputPerM: 12.5,
    outputPerM: 75,
    cacheReadPerM: 1.25,
    cacheWritePerM: 15.625,
    currency: "USD",
  },
  {
    key: "gpt-5.5-pro",
    label: "GPT-5.5 Pro",
    match: /gpt[.\-_]*5[.\-_]*5[.\-_]*pro/i,
    inputPerM: 30,
    outputPerM: 180,
    // Pro 系列官方表无缓存输入价
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5.5-cyber",
    label: "GPT-5.5 Cyber",
    match: /gpt[.\-_]*5[.\-_]*5[.\-_]*cyber/i,
    inputPerM: 12.5,
    outputPerM: 75,
    cacheReadPerM: 1.25,
    cacheWritePerM: 15.625,
    currency: "USD",
  },
  {
    key: "gpt-5.5",
    label: "GPT-5.5",
    match: /gpt[.\-_]*5[.\-_]*5/i,
    inputPerM: 5,
    outputPerM: 30,
    cacheReadPerM: 0.5,
    cacheWritePerM: 6.25,
    currency: "USD",
  },
  {
    key: "gpt-5.4-pro",
    label: "GPT-5.4 Pro",
    match: /gpt[.\-_]*5[.\-_]*4[.\-_]*pro/i,
    inputPerM: 30,
    outputPerM: 180,
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5.4-mini",
    label: "GPT-5.4 mini",
    match: /gpt[.\-_]*5[.\-_]*4[.\-_]*mini/i,
    inputPerM: 0.75,
    outputPerM: 4.5,
    cacheReadPerM: 0.075,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5.4-nano",
    label: "GPT-5.4 nano",
    match: /gpt[.\-_]*5[.\-_]*4[.\-_]*nano/i,
    inputPerM: 0.2,
    outputPerM: 1.25,
    cacheReadPerM: 0.02,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5.4",
    label: "GPT-5.4",
    match: /gpt[.\-_]*5[.\-_]*4/i,
    inputPerM: 2.5,
    outputPerM: 15,
    cacheReadPerM: 0.25,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5.2-pro",
    label: "GPT-5.2 Pro",
    match: /gpt[.\-_]*5[.\-_]*2[.\-_]*pro/i,
    inputPerM: 21,
    outputPerM: 168,
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5.2",
    label: "GPT-5.2",
    match: /gpt[.\-_]*5[.\-_]*2/i,
    inputPerM: 1.75,
    outputPerM: 14,
    cacheReadPerM: 0.175,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5-pro",
    label: "GPT-5 Pro",
    match: /gpt[.\-_]*5[.\-_]*pro/i,
    inputPerM: 15,
    outputPerM: 120,
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5-mini",
    label: "GPT-5 mini",
    match: /gpt[.\-_]*5[.\-_]*mini/i,
    inputPerM: 0.25,
    outputPerM: 2,
    cacheReadPerM: 0.025,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5-nano",
    label: "GPT-5 nano",
    match: /gpt[.\-_]*5[.\-_]*nano/i,
    inputPerM: 0.05,
    outputPerM: 0.4,
    cacheReadPerM: 0.005,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-5.3-codex",
    label: "GPT-5.3 Codex",
    match: /(?:gpt[.\-_]*)?5[.\-_]*3[.\-_]*codex/i,
    inputPerM: 1.75,
    outputPerM: 14,
    cacheReadPerM: 0.175,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    // gpt-5 与 gpt-5.1 同价；放在所有更具体的 gpt-5.x 规则之后兜底
    key: "gpt-5",
    label: "GPT-5 / GPT-5.1",
    match: /gpt[.\-_]*5(?:[.\-_]*1)?\b/i,
    inputPerM: 1.25,
    outputPerM: 10,
    cacheReadPerM: 0.125,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "o4-mini",
    label: "o4-mini / o3-mini",
    match: /\bo[34][.\-_]*mini/i,
    inputPerM: 1.1,
    outputPerM: 4.4,
    cacheReadPerM: 0.275,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "o3-pro",
    label: "o3-pro",
    match: /\bo3[.\-_]*pro/i,
    inputPerM: 20,
    outputPerM: 80,
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "o3",
    label: "o3",
    match: /\bo3\b/i,
    inputPerM: 2,
    outputPerM: 8,
    cacheReadPerM: 0.5,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-4.1-mini",
    label: "GPT-4.1 mini",
    match: /gpt[.\-_]*4[.\-_]*1[.\-_]*mini/i,
    inputPerM: 0.4,
    outputPerM: 1.6,
    cacheReadPerM: 0.1,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-4.1-nano",
    label: "GPT-4.1 nano",
    match: /gpt[.\-_]*4[.\-_]*1[.\-_]*nano/i,
    inputPerM: 0.1,
    outputPerM: 0.4,
    cacheReadPerM: 0.025,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-4.1",
    label: "GPT-4.1",
    match: /gpt[.\-_]*4[.\-_]*1/i,
    inputPerM: 2,
    outputPerM: 8,
    cacheReadPerM: 0.5,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-4o-mini",
    label: "GPT-4o mini",
    match: /gpt[.\-_]*4o[.\-_]*mini/i,
    inputPerM: 0.15,
    outputPerM: 0.6,
    cacheReadPerM: 0.075,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "gpt-4o",
    label: "GPT-4o",
    match: /gpt[.\-_]*4o/i,
    inputPerM: 2.5,
    outputPerM: 10,
    cacheReadPerM: 1.25,
    cacheWritePerM: 0,
    currency: "USD",
  },
];
