import type { PricingRow } from "../pricing";

export const ZHIPU_PRICING: PricingRow[] = [
  // ==========================================================================
  // 智谱 GLM — docs.z.ai/guides/overview/pricing（海外站，美元；核对 2026-10-08）
  //
  // 缓存写入官方标注「限时免费」，故 cacheWritePerM 全填 0，是事实不是占位。
  // -flash 免费款必须排在同系列付费款之前。
  // 注意 GLM-5.3-Flash **不是**免费款（$0.15/$0.50），与 4.7-Flash 不同。
  // ==========================================================================
  {
    // 2026-10 新增。flash / flashx 都必须排在宽松的 glm-5.3 之前，
    // 否则会按 GLM-5.3 的 $1.4/$4.4 计费
    key: "glm-5.3-flashx",
    label: "GLM-5.3-FlashX",
    match: /glm[.\-_]*5[.\-_]*3[.\-_]*flashx/i,
    inputPerM: 0.37,
    outputPerM: 1.25,
    cacheReadPerM: 0.075,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    // 2026-10 新增
    key: "glm-5.3-flash",
    label: "GLM-5.3-Flash",
    match: /glm[.\-_]*5[.\-_]*3[.\-_]*flash/i,
    inputPerM: 0.15,
    outputPerM: 0.5,
    cacheReadPerM: 0.03,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-5.3",
    label: "GLM-5.3",
    match: /glm[.\-_]*5[.\-_]*3/i,
    inputPerM: 1.4,
    outputPerM: 4.4,
    cacheReadPerM: 0.26,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-5.2",
    label: "GLM-5.2",
    match: /glm[.\-_]*5[.\-_]*2/i,
    inputPerM: 1.4,
    outputPerM: 4.4,
    cacheReadPerM: 0.26,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-5.1",
    label: "GLM-5.1",
    match: /glm[.\-_]*5[.\-_]*1/i,
    inputPerM: 1.4,
    outputPerM: 4.4,
    cacheReadPerM: 0.26,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    // 2026-10 核对时官方价格页已不再列出，价格保持上次核对值，用于历史用量换算
    key: "glm-5-turbo",
    label: "GLM-5-Turbo",
    match: /glm[.\-_]*5[.\-_]*turbo/i,
    inputPerM: 1.2,
    outputPerM: 4,
    cacheReadPerM: 0.24,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    // 2026-10 核对时官方价格页已不再列出，价格保持上次核对值，用于历史用量换算
    key: "glm-5v-turbo",
    label: "GLM-5V-Turbo",
    match: /glm[.\-_]*5v[.\-_]*turbo/i,
    inputPerM: 1.2,
    outputPerM: 4,
    cacheReadPerM: 0.24,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.7-flash",
    label: "GLM-4.7-Flash (免费)",
    match: /glm[.\-_]*4[.\-_]*7[.\-_]*flash(?![.\-_]*x)/i,
    inputPerM: 0,
    outputPerM: 0,
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.7-flashx",
    label: "GLM-4.7-FlashX",
    match: /glm[.\-_]*4[.\-_]*7[.\-_]*flashx/i,
    inputPerM: 0.07,
    outputPerM: 0.4,
    cacheReadPerM: 0.01,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.7",
    label: "GLM-4.7",
    match: /glm[.\-_]*4[.\-_]*7/i,
    inputPerM: 0.6,
    outputPerM: 2.2,
    cacheReadPerM: 0.11,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-5",
    label: "GLM-5",
    match: /glm[.\-_]*5\b/i,
    inputPerM: 1,
    outputPerM: 3.2,
    cacheReadPerM: 0.2,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.6v-flash",
    label: "GLM-4.6V-Flash (免费)",
    match: /glm[.\-_]*4[.\-_]*6v[.\-_]*flash(?![.\-_]*x)/i,
    inputPerM: 0,
    outputPerM: 0,
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    // 2026-10 新增；须排在宽松的 glm-4.6v 之前
    key: "glm-4.6v-flashx",
    label: "GLM-4.6V-FlashX",
    match: /glm[.\-_]*4[.\-_]*6v[.\-_]*flashx/i,
    inputPerM: 0.04,
    outputPerM: 0.4,
    cacheReadPerM: 0.004,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.6v",
    label: "GLM-4.6V",
    match: /glm[.\-_]*4[.\-_]*6v/i,
    inputPerM: 0.3,
    outputPerM: 0.9,
    cacheReadPerM: 0.05,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.5-flash",
    label: "GLM-4.5-Flash (免费)",
    match: /glm[.\-_]*4[.\-_]*5[.\-_]*flash/i,
    inputPerM: 0,
    outputPerM: 0,
    cacheReadPerM: 0,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.5-airx",
    label: "GLM-4.5-AirX",
    match: /glm[.\-_]*4[.\-_]*5[.\-_]*airx/i,
    inputPerM: 1.1,
    outputPerM: 4.5,
    cacheReadPerM: 0.22,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.5-air",
    label: "GLM-4.5-Air",
    match: /glm[.\-_]*4[.\-_]*5[.\-_]*air/i,
    inputPerM: 0.2,
    outputPerM: 1.1,
    cacheReadPerM: 0.03,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.5-x",
    label: "GLM-4.5-X",
    match: /glm[.\-_]*4[.\-_]*5[.\-_]*x\b/i,
    inputPerM: 2.2,
    outputPerM: 8.9,
    cacheReadPerM: 0.45,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    key: "glm-4.5v",
    label: "GLM-4.5V",
    match: /glm[.\-_]*4[.\-_]*5v/i,
    inputPerM: 0.6,
    outputPerM: 1.8,
    cacheReadPerM: 0.11,
    cacheWritePerM: 0,
    currency: "USD",
  },
  {
    // GLM-4.5 与 GLM-4.6 同价；放在所有 4.5-* / 4.6v 变体之后兜底
    key: "glm-4.5",
    label: "GLM-4.5 / GLM-4.6",
    match: /glm[.\-_]*4[.\-_]*[56]\b/i,
    inputPerM: 0.6,
    outputPerM: 2.2,
    cacheReadPerM: 0.11,
    cacheWritePerM: 0,
    currency: "USD",
  },
];
